import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import UserLayout from "./UserDashboard/layout";
import PathnameProvider from "./components/PathnameProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // if (pathname.startsWith("/UserDashboard")) {
  //   return <UserLayout>{children}</UserLayout>;
  // }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      ><PathnameProvider>
        {children}
        </PathnameProvider>
        <Toaster />
      </body>
    </html>
  );
}
